### ISSUE TITLE
Double free or corruption with --fromfile option

### ISSUE THREAD

**Issue by Balletie** [inotify-tools/inotify-tools#195]
Hi, after the upgrade from version 3.22.6.0 to 4.23 on up, my watch script stopped working. It's using the `--fromfile` option like so:

```
while git ls-files | inotifywait -e close_write --fromfile -; do
    make
done
```

Error output:
```
Couldn't watch 	ڴU: No such file or directory
double free or corruption (out)
```

I saw that between those versions the project converted its source code from C to C++.

I'm using Arch linux.

**Comment by ericcurtin** [comment]
Could you build a debug version of this and run the exact same thing through a tool like valgrind or gdb? You'll likely get a backtrace of where the double free happened.

**Comment by Balletie** [comment]
Hi, here's the backtrace. The double-free occurs in FileList's destructor...

```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007fada68ac8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007fada685c668 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fada68444b8 in __GI_abort () at abort.c:79
#4  0x00007fada6845390 in __libc_message (fmt=fmt@entry=0x7fada69bc55d "%s\n") at ../sysdeps/posix/libc_fatal.c:150
#5  0x00007fada68b67b7 in malloc_printerr (str=str@entry=0x7fada69bf3c8 "double free or corruption (out)") at malloc.c:5765
#6  0x00007fada68b8830 in _int_free_merge_chunk (av=0x7fada69f6ac0 <main_arena>, p=0x555a1e520330, size=93845544278224) at malloc.c:4669
#7  0x00007fada68b89c7 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>, have_lock@entry=0) at malloc.c:4639
#8  0x00007fada68bb353 in __GI___libc_free (mem=<optimized out>) at malloc.c:3391
#9  0x0000555a1d99a776 in FileList::~FileList (this=<optimized out>, this=<optimized out>) at /usr/src/debug/inotify-tools/inotify-tools-4.23.9.0/src/common.cpp:62
#10 0x0000555a1d9995ce in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/inotify-tools/inotify-tools-4.23.9.0/src/inotifywait.cpp:479
```

And valgrind output:

```
==8035== Memcheck, a memory error detector
==8035== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==8035== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==8035== Command: inotifywait -e close_write --fromfile -
==8035== 
==8035== Invalid write of size 8
==8035==    at 0x10B92B: construct_path_list(int, char**, char const*, FileList*) (common.cpp:141)
==8035==    by 0x10A45C: main (inotifywait.cpp:240)
==8035==  Address 0x4e311a0 is 0 bytes after a block of size 8,192 alloc'd
==8035==    at 0x4841848: malloc (vg_replace_malloc.c:431)
==8035==    by 0x10B830: construct_path_list(int, char**, char const*, FileList*) (common.cpp:118)
==8035==    by 0x10A45C: main (inotifywait.cpp:240)
==8035== 
==8035== Invalid write of size 8
==8035==    at 0x10B9D9: construct_path_list(int, char**, char const*, FileList*) (common.cpp:159)
==8035==    by 0x10A45C: main (inotifywait.cpp:240)
==8035==  Address 0x4e3e2d0 is 6 bytes after a block of size 58 alloc'd
==8035==    at 0x4841848: malloc (vg_replace_malloc.c:431)
==8035==    by 0x4BEC3DE: strdup (strdup.c:42)
==8035==    by 0x10B920: construct_path_list(int, char**, char const*, FileList*) (common.cpp:141)
==8035==    by 0x10A45C: main (inotifywait.cpp:240)
==8035== 
Setting up watches.
Couldn't watch : No such file or directory
==8035== Invalid read of size 8
==8035==    at 0x10B77A: FileList::~FileList() (common.cpp:61)
==8035==    by 0x10A5CD: main (inotifywait.cpp:479)
==8035==  Address 0x4e311a0 is 0 bytes after a block of size 8,192 alloc'd
==8035==    at 0x4841848: malloc (vg_replace_malloc.c:431)
==8035==    by 0x10B830: construct_path_list(int, char**, char const*, FileList*) (common.cpp:118)
==8035==    by 0x10A45C: main (inotifywait.cpp:240)
==8035== 
==8035== 
==8035== HEAP SUMMARY:
==8035==     in use at exit: 247,818 bytes in 6,689 blocks
==8035==   total heap usage: 7,725 allocs, 1,036 frees, 393,081 bytes allocated
==8035== 
==8035== 247,746 bytes in 6,686 blocks are definitely lost in loss record 4 of 4
==8035==    at 0x4841848: malloc (vg_replace_malloc.c:431)
==8035==    by 0x4BEC3DE: strdup (strdup.c:42)
==8035==    by 0x10B920: construct_path_list(int, char**, char const*, FileList*) (common.cpp:141)
==8035==    by 0x10A45C: main (inotifywait.cpp:240)
==8035== 
==8035== LEAK SUMMARY:
==8035==    definitely lost: 247,746 bytes in 6,686 blocks
==8035==    indirectly lost: 0 bytes in 0 blocks
==8035==      possibly lost: 0 bytes in 0 blocks
==8035==    still reachable: 72 bytes in 3 blocks
==8035==         suppressed: 0 bytes in 0 blocks
==8035== Reachable blocks (those to which a pointer was found) are not shown.
==8035== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==8035== 
==8035== For lists of detected and suppressed errors, rerun with: -s
==8035== ERROR SUMMARY: 3260 errors from 4 contexts (suppressed: 0 from 0)
```

**Comment by Balletie** [comment]
How about this?

```sh
#!/bin/sh

test_description="Issue #195
When --fromfile is used with a list of a large number of files, it shouldn't crash
"

. ./sharness.sh

logfile="log"

run_() {
    # Setup a temp directory with a lot of temp files.
    tmp_dir=$(mktemp -d inotifywait-test-fromfile-XXXXXXXXX)
    for i in $(seq 2600); do
        mktemp -p "${tmp_dir}" test-file-XXX > /dev/null
    done
    logfile="$(realpath $logfile)"
    timeout=2 &&
    touch $logfile "${tmp_dir}"/test-file &&
    {(sleep 1 && chmod 777 "${tmp_dir}"/test-file)&}

    { cd "${tmp_dir}"; ls -1 | xargs realpath | $* \
        --quiet \
        --daemon \
        --outfile $logfile \
        --event ATTRIB \
        --fromfile - && sleep $timeout; }
    # No way to use 'wait' for a process that is not a child of this one,
    # sleep instead until inotifywait's timeout is reached.}
}

run_and_check_log()
{
    rm -f $logfile
    run_ $* && grep "ATTRIB \$" $logfile
}

test_expect_success 'exit success' '
    run_and_check_log inotifywait
'

test_done
```

**Comment by ericcurtin** [comment]
LGTM, free free to open a PR and you can be inotify-tools latest contributor :smile:

**Comment by Balletie** [comment]
I was unavailable for about a month but I opened a PR that contains the above test.

**Comment by ericcurtin** [comment]
Perfect, thanks very much! We can't really give any deadline for this to be fix, we are completely unfunded, but hopefully someone has the time to get around to it soon.

**Comment by gkatev** [comment]
It appears that this has since been fixed in #230? Tested with 4.25.9.0, no longer encountering the issue.
