### ISSUE TITLE
A memory leak detected in program inotifywait

### ISSUE THREAD

**Issue by fCorleone** [inotify-tools/inotify-tools#94]
An issue has been detected when running program inotifywait in ./src/.libs/
```
=================================================================
==5097==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8192 byte(s) in 1 object(s) allocated from:
    #0 0x7f2e4f4a4602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x408d16 in construct_path_list /home/mfc_fuzz/newprogram/inotify-tools/src/common.c:76

Direct leak of 8192 byte(s) in 1 object(s) allocated from:
    #0 0x7f2e4f4a4602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x408d23 in construct_path_list /home/mfc_fuzz/newprogram/inotify-tools/src/common.c:77
```

**Comment by ericcurtin** [comment]
Could you describe the circumstances in which inotifywait was running in this case? @fCorleone
